name: tinqin_interview_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  # Core
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  collection: any
  freezed_annotation: ^2.4.1
  get: ^4.6.5
  dio: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  mocktail: ^1.0.2
  build_runner: ^2.4.9
  freezed: ^2.5.1
  test: ^1.17.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
